version: '3.8'

services:
  web:
    image: djangoforge:latest  # Utilizza l'immagine pre-build presente nel registry
    container_name: web
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 90
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./config/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/.env

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_volume:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web

### MODIFICA L'EMAIL E IL DOMINIO IN ENTRYPOINT!!!
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_volume:/etc/letsencrypt
      - ./config:/etc/letsencrypt/config
      - certbot_webroot:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --domains ${CERTBOT_DOMAINS}; sleep 12h & wait $${!}; done;"
    environment:
      - CERTBOT_EMAIL=leonardobitto@gmail.com
      - CERTBOT_DOMAINS=h1v3.xyz


volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_volume:
  certbot_webroot:  