# Generated by Django 5.0 on 2024-11-02 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('response_code', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AggregatedAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Aggregated Access Log',
                'verbose_name_plural': 'Aggregated Access Logs',
            },
        ),
        migrations.CreateModel(
            name='AggregatedErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Aggregated Error Log',
                'verbose_name_plural': 'Aggregated Error Logs',
            },
        ),
        migrations.CreateModel(
            name='CRMMontlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_suppliers', models.IntegerField(blank=True, null=True)),
                ('total_customers', models.IntegerField(blank=True, null=True)),
                ('total_leads', models.IntegerField(blank=True, null=True)),
                ('total_active_customers', models.IntegerField(blank=True, null=True)),
                ('total_inactive_customers', models.IntegerField(blank=True, null=True)),
                ('total_loyal_customers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CRM Monthly Snapshot',
                'verbose_name_plural': 'CRM Monthly Snapshots',
            },
        ),
        migrations.CreateModel(
            name='ErrorRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('response_code', models.PositiveIntegerField()),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryDailyAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('distinct_products_in_stock', models.IntegerField(blank=True, null=True)),
                ('total_stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_sold_units', models.IntegerField(blank=True, null=True)),
                ('total_sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_sales', models.IntegerField(blank=True, null=True)),
                ('total_delivered_sales', models.IntegerField(blank=True, null=True)),
                ('total_paid_sales', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_sales', models.IntegerField(blank=True, null=True)),
                ('total_ordered_units', models.IntegerField(blank=True, null=True)),
                ('total_orders_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_orders', models.IntegerField(blank=True, null=True)),
                ('total_delivered_orders', models.IntegerField(blank=True, null=True)),
                ('total_paid_orders', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_orders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Daily Aggregation',
                'verbose_name_plural': 'Inventory Daily Aggregations',
            },
        ),
        migrations.CreateModel(
            name='InventoryMonthlyAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('distinct_products_in_stock', models.IntegerField(blank=True, null=True)),
                ('total_stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_sold_units', models.IntegerField(blank=True, null=True)),
                ('total_sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_sales', models.IntegerField(blank=True, null=True)),
                ('total_delivered_sales', models.IntegerField(blank=True, null=True)),
                ('total_paid_sales', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_sales', models.IntegerField(blank=True, null=True)),
                ('total_ordered_units', models.IntegerField(blank=True, null=True)),
                ('total_orders_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_orders', models.IntegerField(blank=True, null=True)),
                ('total_delivered_orders', models.IntegerField(blank=True, null=True)),
                ('total_paid_orders', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_orders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Monthly Aggregation',
                'verbose_name_plural': 'Inventory Monthly Aggregations',
            },
        ),
        migrations.CreateModel(
            name='InventoryMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_products', models.IntegerField(blank=True, null=True)),
                ('total_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('total_stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('average_stock_per_product', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Monthly Snapshot',
                'verbose_name_plural': 'Inventory Monthly Snapshots',
            },
        ),
        migrations.CreateModel(
            name='InventoryQualityAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('products_missing_category', models.IntegerField(blank=True, null=True)),
                ('products_missing_image', models.IntegerField(blank=True, null=True)),
                ('products_missing_description', models.IntegerField(blank=True, null=True)),
                ('products_missing_both', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Quality Aggregation',
                'verbose_name_plural': 'Inventory Quality Aggregations',
            },
        ),
        migrations.CreateModel(
            name='InventoryQuarterlyAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('distinct_products_in_stock', models.IntegerField(blank=True, null=True)),
                ('total_stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_sold_units', models.IntegerField(blank=True, null=True)),
                ('total_sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_sales', models.IntegerField(blank=True, null=True)),
                ('total_delivered_sales', models.IntegerField(blank=True, null=True)),
                ('total_paid_sales', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_sales', models.IntegerField(blank=True, null=True)),
                ('total_ordered_units', models.IntegerField(blank=True, null=True)),
                ('total_orders_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_orders', models.IntegerField(blank=True, null=True)),
                ('total_delivered_orders', models.IntegerField(blank=True, null=True)),
                ('total_paid_orders', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_orders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Quarterly Aggregation',
                'verbose_name_plural': 'Inventory Quarterly Aggregations',
            },
        ),
        migrations.CreateModel(
            name='InventoryWeeklyAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('distinct_products_in_stock', models.IntegerField(blank=True, null=True)),
                ('total_stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_sold_units', models.IntegerField(blank=True, null=True)),
                ('total_sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_sales', models.IntegerField(blank=True, null=True)),
                ('total_delivered_sales', models.IntegerField(blank=True, null=True)),
                ('total_paid_sales', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_sales', models.IntegerField(blank=True, null=True)),
                ('total_ordered_units', models.IntegerField(blank=True, null=True)),
                ('total_orders_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_orders', models.IntegerField(blank=True, null=True)),
                ('total_delivered_orders', models.IntegerField(blank=True, null=True)),
                ('total_paid_orders', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_orders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Weekly Aggregation',
                'verbose_name_plural': 'Inventory Weekly Aggregations',
            },
        ),
        migrations.CreateModel(
            name='InventoryYearlyAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('distinct_products_in_stock', models.IntegerField(blank=True, null=True)),
                ('total_stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_sold_units', models.IntegerField(blank=True, null=True)),
                ('total_sales_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_sales', models.IntegerField(blank=True, null=True)),
                ('total_delivered_sales', models.IntegerField(blank=True, null=True)),
                ('total_paid_sales', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_sales', models.IntegerField(blank=True, null=True)),
                ('total_ordered_units', models.IntegerField(blank=True, null=True)),
                ('total_orders_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_pending_orders', models.IntegerField(blank=True, null=True)),
                ('total_delivered_orders', models.IntegerField(blank=True, null=True)),
                ('total_paid_orders', models.IntegerField(blank=True, null=True)),
                ('total_cancelled_orders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Yearly Aggregation',
                'verbose_name_plural': 'Inventory Yearly Aggregations',
            },
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.AddIndex(
            model_name='accessrequestlog',
            index=models.Index(fields=['timestamp'], name='logging_app_timesta_bbbb81_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequestlog',
            index=models.Index(fields=['request_path'], name='logging_app_request_b7853c_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequestlog',
            index=models.Index(fields=['response_code'], name='logging_app_respons_52dde2_idx'),
        ),
        migrations.AddIndex(
            model_name='errorrequestlog',
            index=models.Index(fields=['timestamp'], name='logging_app_timesta_19d93f_idx'),
        ),
        migrations.AddIndex(
            model_name='errorrequestlog',
            index=models.Index(fields=['request_path'], name='logging_app_request_d6662c_idx'),
        ),
        migrations.AddIndex(
            model_name='errorrequestlog',
            index=models.Index(fields=['response_code'], name='logging_app_respons_2244f1_idx'),
        ),
    ]
