# Generated by Django 4.1.7 on 2023-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=100)),
                ('header', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_first', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.CharField(blank=True, max_length=200, null=True)),
                ('weekend', models.CharField(blank=True, max_length=300, null=True)),
                ('closing_day', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
