# Generated by Django 4.1.7 on 2023-09-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_image',
            name='header',
        ),
    ]
