# Generated by Django 4.1.7 on 2023-09-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_gallery_image_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_image',
            name='img',
        ),
    ]
