# Generated by Django 4.1.7 on 2023-09-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_gallery_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_image',
            name='img',
        ),
    ]
