# Generated by Django 4.1.7 on 2023-09-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_carousel_image_delete_gallery_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='Gallery',
        ),
    ]
