# Generated by Django 4.1.7 on 2023-09-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_carousel_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='carousel',
            new_name='gallery',
        ),
    ]
