theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 


description: "Official documentation for the DjangoForge project."
logo: "./assets/img/DjangoForge.png"
favicon: "./assets/img/djangoforgeico.svg"
show_downloads: true
url: "https://leobitto.github.io/DjangoForge" # the base hostname & protocol for your site
baseurl: "/docs" # the subpath of your site, e.g. /blog

# Exclude specific files or directories from being processed by Jekyll
exclude:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md


# Permalinks configuration (optional)
permalink: pretty

# Markdown settings (optional)
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
github:
  is_project_page: true
  project_tagline: "DjangoForge: Modular Django ecosystem for SMEs"

# Navigation (optional)
collections:
  docs:
    output: true
    permalink: /:path/:basename:output_ext

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # Apply a default layout to all files

# Pagination settings (optional)
paginate: 10
paginate_path: "/page:num/"
