name: Deploy Docker Compose

on:
  workflow_call:
    inputs:
      host:
        description: "Host IP Address"
        required: true
      username:
        description: "Username for SSH"
        required: true
      private_key:
        description: "Private Key for SSH"
        required: true
      repo_name:
        description: "Name of the repo"
        required: true
      ghcr_token:
        description: "Token to access repo"
        required: true
      image_name:
        description: "Name of the image"
        required: true

jobs:
  deploy-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ inputs.ghcr_token }}

      - name: SCP Docker Compose file 
        uses: appleboy/scp-action@master
        with:
            host: ${{ inputs.host }}  
            username: ${{ inputs.username }}
            key: ${{ inputs.private_key }}  
            source: "./docker-compose.prod.yml"
            target: "/opt/${{ inputs.repo_name }}/"

      - name: Start containers
        uses: appleboy/ssh-action@v0.1.3
        with:
            host: ${{ inputs.host }}  
            username: ${{ inputs.username }}
            key: ${{ inputs.private_key }}  
        script: |
            echo ${{ inputs.ghcr_token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/leobitto/${{ inputs.image_name }}:latest 

            docker tag ghcr.io/leobitto/${{ inputs.image_name }}:latest ${{ inputs.image_name }}

            mkdir -p /opt/web/static
            mkdir -p /opt/web/media


            docker compose -f /opt/${{ inputs.repo_name }}/docker-compose.prod.yml up -d 
            echo "wait 5 sec for POSTGRES service to fully start"
            sleep 5
            echo "5 seconds has passed"
            docker exec web python manage.py migrate
            docker exec web python manage.py collectstatic --noinput --clear
