name: Test Config and Artifact Mechanism

on:
  workflow_dispatch:

jobs:
  # Job 1: Creazione dei file di configurazione
  create-config:
    runs-on: ubuntu-latest

    steps:
      - name: Creazione della directory di configurazione
        run: mkdir -p config

      - name: Creazione del file di configurazione per Django
        run: |
          echo "DEBUG=${{ secrets.DEBUG }}" >> config/django.cfg
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> config/django.cfg
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> config/django.cfg
          echo "SQL_ENGINE=${{ secrets.SQL_ENGINE }}" >> config/django.cfg
          echo "DATABASE=${{ secrets.DATABASE }}" >> config/django.cfg
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> config/django.cfg

      - name: Creazione del file di configurazione per Postgres (db.cfg)
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> config/db.cfg
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> config/db.cfg
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> config/db.cfg
          echo "SQL_HOST=${{ secrets.SQL_HOST }}" >> config/db.cfg
          echo "SQL_PORT=${{ secrets.SQL_PORT }}" >> config/db.cfg

      - name: Creazione del file di configurazione per Gold Postgres (gold.cfg)
        run: |
          echo "GOLD_POSTGRES_DB=${{ secrets.GOLD_POSTGRES_DB }}" >> config/gold.cfg
          echo "GOLD_POSTGRES_USER=${{ secrets.GOLD_POSTGRES_USER }}" >> config/gold.cfg
          echo "GOLD_POSTGRES_PASSWORD=${{ secrets.GOLD_POSTGRES_PASSWORD }}" >> config/gold.cfg
          echo "GOLD_SQL_HOST=${{ secrets.GOLD_SQL_HOST }}" >> config/gold.cfg
          echo "GOLD_SQL_PORT=${{ secrets.GOLD_SQL_PORT }}" >> config/gold.cfg

      - name: Salva file di configurazione come artifact
        uses: actions/upload-artifact@v3
        with:
          name: config-files
          path: ./config/

  # Job 2: Lettura e visualizzazione degli artifacts
  read-config:
    runs-on: ubuntu-latest
    needs: create-config  # Dipende dal Job 1

    steps:
      - name: Scarica i file di configurazione
        uses: actions/download-artifact@v3
        with:
          name: config-files

      - name: Mostra il contenuto del file Django (django.cfg)
        run: cat ./config/django.cfg

      - name: Mostra il contenuto del file di configurazione per Postgres (db.cfg)
        run: cat ./config/db.cfg

      - name: Mostra il contenuto del file di configurazione per Gold Postgres (gold.cfg)
        run: cat ./config/gold.cfg
