name: DEbug

on:
  workflow_dispatch:  # Trigger manual workflow run

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: djangoforge


jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: recursive
            token: ${{ secrets.GHCR_TOKEN }}

      - name : debug
        run : |
          # Estrai il valore del segreto in una variabile
          DOMAINS=echo ${{ secrets.DOMAINS }} | sed 's/ /,/g'              
          echo $DOMAINS
        
